import path from "node:path"
import { format } from "prettier"

type Contract = {
  identity: string
  host: string
  path: readonly string[]
  aliases: readonly (readonly string[])[]
  title: string
  category: string
  availability: string
  inputBoundary: string
}

type Entry = {
  sourceRef: string
  contractVersion: number
  contract: Contract
}

type Catalog = {
  version: number
  commands: Record<string, Entry>
}

const required = ["appExit", "sessionRename"] as const
const directory = path.resolve(import.meta.dir, "..")
const catalogFile = path.join(directory, "src/command-toolkit/upstream-catalog.json")
const outputFile = path.join(directory, "src/command-toolkit/upstream-current.gen.ts")

export function validateUpstreamCommandCatalog(input: unknown): asserts input is Catalog {
  if (!input || typeof input !== "object") throw new Error("Upstream command catalog must be an object")
  const catalog = input as Partial<Catalog>
  if (catalog.version !== 1 || !catalog.commands || typeof catalog.commands !== "object")
    throw new Error("Unsupported upstream command catalog")
  for (const name of required) {
    const entry = catalog.commands[name]
    if (!entry) throw new Error(`Missing required upstream command ${name}`)
    if (!/^[0-9a-f]{12}$/.test(entry.sourceRef)) throw new Error(`Invalid upstream source ref for ${name}`)
    if (!Number.isSafeInteger(entry.contractVersion) || entry.contractVersion < 1)
      throw new Error(`Invalid contract version for ${name}`)
    validateContract(name, entry.contract)
  }
}

export async function renderUpstreamCommandManifest(catalog: Catalog) {
  validateUpstreamCommandCatalog(catalog)
  const entries = Object.entries(catalog.commands)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, entry]) => {
      const contract = JSON.stringify(entry.contract, null, 2)
        .split("\n")
        .map((line) => `    ${line}`)
        .join("\n")
      const fingerprint = `${entry.sourceRef}:${entry.contract.identity}:v${entry.contractVersion}`
      return `  ${name}: defineUpstreamCommand(\n${contract},\n    ${JSON.stringify(fingerprint)},\n  ),`
    })
    .join("\n")
  return format(
    `// Generated by script/generate-upstream-command-manifest.ts. Do not edit.\nimport { defineUpstreamCommand } from "@opencode-ai/command-kit"\n\nexport const currentUpstreamCommands = {\n${entries}\n} as const\n`,
    { parser: "typescript", printWidth: 120, semi: false },
  )
}

function validateContract(name: string, input: unknown): asserts input is Contract {
  if (!input || typeof input !== "object") throw new Error(`Invalid contract for ${name}`)
  const contract = input as Partial<Contract>
  const strings = [
    contract.identity,
    contract.host,
    contract.title,
    contract.category,
    contract.availability,
    contract.inputBoundary,
  ]
  if (strings.some((value) => typeof value !== "string" || !value)) throw new Error(`Invalid contract for ${name}`)
  if (
    !Array.isArray(contract.path) ||
    !contract.path.length ||
    contract.path.some((value) => typeof value !== "string")
  )
    throw new Error(`Invalid path for ${name}`)
  if (
    !Array.isArray(contract.aliases) ||
    contract.aliases.some(
      (alias) => !Array.isArray(alias) || !alias.length || alias.some((value) => typeof value !== "string"),
    )
  )
    throw new Error(`Invalid aliases for ${name}`)
}

if (import.meta.main) {
  const catalog: unknown = await Bun.file(catalogFile).json()
  validateUpstreamCommandCatalog(catalog)
  const generated = await renderUpstreamCommandManifest(catalog)
  if (!process.argv.includes("--check")) await Bun.write(outputFile, generated)
  else if ((await Bun.file(outputFile).text()) !== generated) {
    console.error("Upstream command manifest is stale. Run bun run generate:upstream-commands in packages/tui.")
    process.exit(1)
  }
}
